// Code generated by goctl. DO NOT EDIT.
// Source: good.proto

package server

import (
	"context"

	"zero_shop/app/goods/cmd/rpc/good"
	"zero_shop/app/goods/cmd/rpc/internal/logic"
	"zero_shop/app/goods/cmd/rpc/internal/svc"
)

type GoodServer struct {
	svcCtx *svc.ServiceContext
	good.UnimplementedGoodServer
}

func NewGoodServer(svcCtx *svc.ServiceContext) *GoodServer {
	return &GoodServer{
		svcCtx: svcCtx,
	}
}

func (s *GoodServer) CreateGood(ctx context.Context, in *good.CreateGoodRequest) (*good.CreateGoodResponse, error) {
	l := logic.NewCreateGoodLogic(ctx, s.svcCtx)
	return l.CreateGood(in)
}

func (s *GoodServer) FindGoodPage(ctx context.Context, in *good.FindGoodRequest) (*good.FindGoodResponse, error) {
	l := logic.NewFindGoodPageLogic(ctx, s.svcCtx)
	return l.FindGoodPage(in)
}
