// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package server

import (
	"context"

	"zero_shop/app/user/cmd/rpc/internal/logic"
	"zero_shop/app/user/cmd/rpc/internal/svc"
	"zero_shop/app/user/cmd/rpc/user"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	user.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServer) Login(ctx context.Context, in *user.LoginRequest) (*user.LoginResponse, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

func (s *UserServer) Register(ctx context.Context, in *user.RegisterRequest) (*user.RegisterResponse, error) {
	l := logic.NewRegisterLogic(ctx, s.svcCtx)
	return l.Register(in)
}

func (s *UserServer) SendEmail(ctx context.Context, in *user.SendEmailRequest) (*user.SendEmailResponse, error) {
	l := logic.NewSendEmailLogic(ctx, s.svcCtx)
	return l.SendEmail(in)
}

func (s *UserServer) GetUserMsg(ctx context.Context, in *user.GetUserMsgRequest) (*user.GetUserMsgResponse, error) {
	l := logic.NewGetUserMsgLogic(ctx, s.svcCtx)
	return l.GetUserMsg(in)
}
