// Code generated by goctl. DO NOT EDIT.
// Source: payment.proto

package server

import (
	"context"
	"zero_shop/app/payment/internal/logic"
	"zero_shop/app/payment/internal/svc"
	"zero_shop/app/payment/payment"
)

type PaymentServer struct {
	svcCtx *svc.ServiceContext
	payment.UnimplementedPaymentServer
}

func NewPaymentServer(svcCtx *svc.ServiceContext) *PaymentServer {
	return &PaymentServer{
		svcCtx: svcCtx,
	}
}

func (s *PaymentServer) Ping(ctx context.Context, in *payment.Request) (*payment.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
